# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Olivia
title-normal: Zhao
email: olivia.fangyun.zhao@gmail.com
description: An Undergraduate Researcher in Psychology and Robotics
baseurl: # the subpath of your site, e.g. /blog
url: "https://fangyunzhao.github.io" # the base hostname & protocol for your site
author: Olivia Zhao
street_address: 
city: 
state: 
zip_code: 
country: 
phone: (608)886-3284

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 7

# Social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: 
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
